# Copyright (c) 2026 Joseph Verdicchio and DiscOS  Contributors
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import random
import time

import grpc

# Generated by grpc_tools.protoc:
import evidenceos_pb2
import evidenceos_pb2_grpc


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--endpoint", default="127.0.0.1:50051")
    ap.add_argument("--seed", type=int, default=123)
    ap.add_argument("--n", type=int, default=64)
    args = ap.parse_args()

    channel = grpc.insecure_channel(args.endpoint)
    stub = evidenceos_pb2_grpc.EvidenceOSStub(channel)

    h = stub.Health(evidenceos_pb2.HealthRequest())
    print({"health": h.status})

    sess = stub.CreateSession(
        evidenceos_pb2.CreateSessionRequest(
            alpha=0.05,
            epoch_size=10_000,
            hysteresis_delta=0.0,
            oracle_buckets=256,
            joint_bits_budget=0,
            binom_p1=0.6,
        )
    )
    print({"session_id": sess.session_id})

    hold = stub.InitHoldout(
        evidenceos_pb2.InitHoldoutRequest(
            session_id=sess.session_id,
            kind=evidenceos_pb2.HOLDOUT_KIND_LABELS,
            seed=args.seed,
            size=args.n,
        )
    )
    print({"holdout_id": hold.holdout_id})

    # Random predictions.
    preds = bytes([random.randint(0, 1) for _ in range(args.n)])

    r = stub.OracleAccuracy(
        evidenceos_pb2.OracleAccuracyRequest(
            session_id=sess.session_id,
            holdout_id=hold.holdout_id,
            predictions=preds,
        )
    )
    print(
        {
            "oracle_bucket": r.bucket,
            "num_buckets": r.num_buckets,
            "k_bits_total": r.k_bits_total,
            "barrier": r.barrier,
            "frozen": r.frozen,
        }
    )

    led = stub.GetLedger(evidenceos_pb2.GetLedgerRequest(session_id=sess.session_id))
    print(
        {
            "alpha": led.alpha,
            "alpha_prime": led.alpha_prime,
            "k_bits_total": led.k_bits_total,
            "barrier": led.barrier,
            "wealth": led.wealth,
            "events": [
                {"kind": e.kind, "bits": e.bits, "meta": e.json_meta} for e in led.events
            ],
        }
    )

    etl = stub.GetEtlRoot(evidenceos_pb2.GetEtlRootRequest())
    print({"etl_root": etl.root_hash_hex, "tree_size": etl.tree_size})


if __name__ == "__main__":
    main()
