name: Feature request
description: Propose an improvement to DiscOS.
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe expected behavior and UX/CLI impact.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered

  - type: checkboxes
    id: quality
    attributes:
      label: Design quality checklist
      options:
        - label: Proposal can be validated by black-box tests.
          required: true
        - label: Proposal addresses boundary cases and failure modes.
          required: true
        - label: Proposal preserves deterministic behavior where applicable.
          required: true
        - label: Proposal avoids copy-paste logic and favors shared abstractions.
          required: true
